# Generated by Django 5.0.4 on 2025-07-27 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=40)),
                ('tracking', models.CharField(max_length=80, unique=True)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('transito', 'En tránsito'), ('entregado', 'Entregado')], default='preparando', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='pedidos.orden')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-creado'],
            },
        ),
    ]
